# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-SMS-MessageNet
version:      0.60
version_from: lib/Net/SMS/MessageNet.pm
installdirs:  site
requires:
    HTTP::Cookies:                 0
    LWP:                           0
    Test::More:                    0
    URI::Escape:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
